version: '3.8'

services:
  app:
    build:
      context: .
    depends_on:
      - mongo
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=tfood

  mongo:
    image: 'mongo:latest'
    restart: always
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27018:27017"