version: '3.8'

services:
  app:
    container_name: tfood_main
    build:
      context: .
    ports:
      - "8081:8080"
    environment:
#      - SPRING_DATA_MONGODB_HOST=tfood.tpmmc.mongodb.net
#      - SPRING_DATA_MONGODB_DATABASE=tfood
#      - SPRING_DATA_MONGODB_USERNAME=${MONGO_USER}
#      - SPRING_DATA_MONGODB_PASSWORD=${MONGO_PASSWORD}
      - SPRING_DATA_MONGODB_URI=${MONGO_URI}
    tty: true

#  mongo:
#    image: 'mongo:latest'
#    container_name: tfood_mongo
#    restart: always
#    volumes:
#      - ./data/mongo:/data/db
#    ports:
#      - "27018:27017"
#    tty: true

#  redis:
#    container_name: tfood_redis
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    volumes:
#      - ./data/redis:/data
#      - ./redis.conf:/usr/local/etc/redis/redis.conf
#    restart: always